AwsTemplateFormatVersion: 2010-09-09
Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "users"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "id"
        - AttributeType: "S"
        - AttributeName: "nombre"
        - AttributeType: "S"
        - AttributeName: "email"
        - AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
        - KeyType: "HASH"


       